### ISSUE TITLE
cant start

### ISSUE THREAD

**Issue by igiteam** [lithtechex/RezExtract#1]
Download premake5 for windows from https://premake.github.io/download, copy the executable to the same location where premake5.lua is located, use .\premake5.exe vs2022.

Just open the solution and compile for the desired architecture/configuration (c++20 required).

I did this, opened the project in vs2022, but when i click on debug, it gives an errorSeverity	Code	Description	Project	File	Line	Suppression State	Details
Error	C2664	'auto std::make_format_args<std::format_context,_Ty>(_Ty &)': cannot convert argument 1 from '_Ty' to '_Ty &'
        with
        [
            _Ty=ULONG
        ]	RezExtract	C:\Users\source\Desktop\UE3BEAST\UNPACKED_RESOURCES\NAVY SEALS\RezExtract-main\RezExtract-main\inc\pch.hpp	57

**Comment by no-lith** [comment]
Fixed with 4ccfecf2a7ad946ed603c098ef2af71c764140b1

**Comment by igiteam** [comment]
Thanks, it works for NAVY SEALS
